name: Test coverage
on: push
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover 
            uses: orgoro/coverage@v3
            with:
                coverageFile: coverage.xml